### ISSUE TITLE
Error en Apache

### ISSUE THREAD

**Issue by fernandouval** [datauy/DerechosDeEstudiantes-2#87]
Hay un error que hay que revisar, dejo el log: 

[ N 2020-03-02 02:50:29.7847 1850/T4 age/Cor/CoreMain.cpp:1028 ]: Checking whether to disconnect long-running connections for process 27590, application /home/datauy/DerechosDeEstudiantes2 (production)
App 27997 output: Required ruby-2.1.0 is not installed.
App 27997 output: To install do: 'rvm install "ruby-2.1.0"'
[ N 2020-03-02 03:03:44.9071 1850/T4 age/Cor/CoreMain.cpp:1028 ]: Checking whether to disconnect long-running connections for process 28182, application /home/datauy/quesabes_website (production)
App 2731 output: Error during failsafe response: Missing template errors/not_found, application/not_found with {:locale=>[:es], :formats=>[:text], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :arb, :coffee, :jbuilder, :haml]}. Searched in:
App 2731 output:   * "/home/datauy/DerechosDeEstudiantes2/app/views"
App 2731 output:   * "/home/datauy/.rvm/gems/ruby-2.5.0/gems/ckeditor-4.2.4/app/views"
App 2731 output:   * "/home/datauy/.rvm/gems/ruby-2.5.0/gems/activeadmin-2.4.0/app/views"
App 2731 output:   * "/home/datauy/.rvm/gems/ruby-2.5.0/gems/kaminari-core-1.1.1/app/views"
App 2731 output:   * "/home/datauy/.rvm/gems/ruby-2.5.0/gems/devise-4.7.1/app/views"
App 2731 output: 
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/path_set.rb:48:in `find'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/lookup_context.rb:116:in `find'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/renderer/abstract_renderer.rb:20:in `find_template'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:10:in `render'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:44:in `render_template'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:25:in `render'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:103:in `_render_template'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/streaming.rb:219:in `_render_template'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:84:in `render_to_body'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/rendering.rb:25:in `render'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:36:in `render'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
App 2731 output:   /home/datauy/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:36:in `cleanup_view_runtime'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:45:in `render'
App 2731 output:   /home/datauy/DerechosDeEstudiantes2/app/controllers/errors_controller.rb:7:in `not_found'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/rack-2.0.8/lib/rack/method_override.rb:22:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/rack-2.0.8/lib/rack/runtime.rb:22:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/rack-2.0.8/lib/rack/sendfile.rb:111:in `call'
App 2731 output:   /home/datauy/.rvm/gems/ruby-2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
App 2731 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 2731 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_pr
App 2731 output: ocess_next_request'
App 2731 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 2731 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 2731 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by fernandouval** [comment]
Las extensiones que no se encuentran, ej: http://localhost:3000/pepes.jpg no funciona su redireccción 404, dado que exige un 404 con esa extensión (como está hecho hoy). Dejo link a posible solución:
https://stackoverflow.com/questions/2385799/how-to-redirect-to-a-404-in-rails
